-- Insert Trainers
INSERT INTO GYM_USERS (FIRST_NAME, LAST_NAME, USERNAME, PASSWORD, IS_ACTIVE, FAILED_LOGIN_ATTEMPTS, BLOCK_STATUS, BLOCK_START_TIME) VALUES
('Tim', 'Smith', 'Tim.Smith', '123', TRUE, 0, FALSE, NULL),
('Sam', 'Jones', 'Sam.Jones', '123', TRUE, 0, FALSE, NULL),
('John', 'Doe', 'John.Doe', '$2a$12$8HTsQpa2IebN9eAu2p/YPu2y3Tm4fkNx7sMY0N4EpB3me2/yGgkFm', TRUE, 0, FALSE, NULL),
('Jane', 'Smith', 'Jane.Smith', '123', TRUE, 0, FALSE, NULL);

INSERT INTO TRAINEES (DATE_OF_BIRTH, ADDRESS, USER_ID) VALUES
(DATE '2000-02-21', 'address of TRAINEE 1', 3),
(DATE '2000-01-21', 'address of TRAINEE 2', 4);

-- Insert TrainingTypes
INSERT INTO TRAINING_TYPES (TRAINING_TYPE_NAME) VALUES
('CARDIO'),
('STRENGTH'),
('HIIT'),
('YOGA'),
('PILATES'),
('GROUP'),
('PERSONAL');

-- Insert Trainers
INSERT INTO TRAINERS (USER_ID, TRAINING_TYPE_ID) VALUES
(1, 1), -- Tim is a CARDIO trainer
(2, 2); -- Sam is a STRENGTH trainer

-- Insert Trainings
INSERT INTO TRAININGS (TRAINEE_ID, TRAINER_ID, TRAINING_NAME, TRAINING_TYPE_ID, TRAINING_DATE, TRAINING_DURATION) VALUES
(3, 1, 'Cardio Workout', 1, DATE '2024-02-21', 60),
(4, 2, 'Strength Training', 2, DATE '2024-02-22', 45);

INSERT INTO TRAINEES_TRAINERS (TRAINEE_ID, TRAINER_ID) VALUES
(3, 1),
(3, 2),
(4, 1);
