CREATE TABLE IF NOT EXISTS TrainingType (
    TrainingTypeID INT PRIMARY KEY,
    TrainingTypeName VARCHAR(255) NOT NULL
);

--CREATE TABLE IF NOT EXISTS User (
--    UserID INT PRIMARY KEY,
--    FirstName VARCHAR(255) NOT NULL,
--    LastName VARCHAR(255) NOT NULL,
--    Username VARCHAR(255) NOT NULL,
--    Password VARCHAR(255) NOT NULL,
--    IsActive BOOLEAN NOT NULL,
--);
--
--CREATE TABLE IF NOT EXISTS Trainee (
--    TraineeID INT PRIMARY KEY,
--    DateOfBirth DATE,
--    Address VARCHAR(255),
--    UserID INT NOT NULL UNIQUE,
--    FOREIGN KEY (UserID) REFERENCES User(UserID) ON DELETE CASCADE
--);
--
--CREATE TABLE IF NOT EXISTS Trainer (
--    TrainerID INT PRIMARY KEY,
--    TrainingTypeID INT,
--    UserID INT NOT NULL UNIQUE,
--    FOREIGN KEY (TrainingTypeID) REFERENCES TrainingType(TrainingTypeID),
--    FOREIGN KEY (UserID) REFERENCES User(UserID) ON DELETE CASCADE
--);
--
--
--CREATE TABLE IF NOT EXISTS Training (
--    ID INT PRIMARY KEY,
--    TraineeID INT,
--    TrainerID INT,
--    TrainingName VARCHAR(255) NOT NULL,
--    TrainingTypeID INT,
--    TrainingDate DATE NOT NULL,
--    TrainingDuration INT NOT NULL,
--
--);
--
--
--CREATE TABLE IF NOT EXISTS Training_Trainee (
--    TrainingID INT,
--    TraineeID INT,
--    PRIMARY KEY (TrainingID, TraineeID),
--    FOREIGN KEY (TrainingID) REFERENCES Training(TrainingID),
--    FOREIGN KEY (TraineeID) REFERENCES Trainee(TraineeID),
--    UNIQUE (TraineeID)  -- Ensure that each Trainee is associated with a specific Training only once
--);
--
--CREATE TABLE IF NOT EXISTS Training_Trainer (
--    TrainingID INT,
--    TrainerID INT,
--    PRIMARY KEY (TrainingID, TrainerID),
--    FOREIGN KEY (TrainingID) REFERENCES Training(TrainingID),
--    FOREIGN KEY (TrainerID) REFERENCES Trainer(TrainerID),
--    UNIQUE (TrainerID)  -- Ensure that each Trainer is associated with a specific Training only once
--);
--
--CREATE TABLE IF NOT EXISTS Training_TrainingType (
--    TrainingID INT,
--    TrainingTypeID INT,
--    PRIMARY KEY (TrainingID, TrainingTypeID),
--    FOREIGN KEY (TrainingID) REFERENCES Training(TrainingID),
--    FOREIGN KEY (TrainingTypeID) REFERENCES TrainingType(TrainingTypeID),
--    UNIQUE (TrainingTypeID)  -- Ensure that each TrainingType is associated with a specific Training only once
--);
--
--
--
--CREATE TABLE IF NOT EXISTS Trainer_TrainingType (
--    TrainerID INT,
--    TrainingTypeID INT,
--    PRIMARY KEY (TrainerID, TrainingTypeID),
--    FOREIGN KEY (TrainerID) REFERENCES Trainer(TrainerID),
--    FOREIGN KEY (TrainingTypeID) REFERENCES TrainingType(TrainingTypeID)
);