CREATE TABLE IF NOT EXISTS TRAINING_TYPES (
    TRAINING_TYPE_ID SERIAL PRIMARY KEY,
    TRAINING_TYPE_NAME VARCHAR(255) NOT NULL
);


CREATE TABLE IF NOT EXISTS GYM_USERS (
    USER_ID SERIAL PRIMARY KEY,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    USERNAME VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    IS_ACTIVE BOOLEAN NOT NULL
);


CREATE TABLE IF NOT EXISTS CUSTOMERS (
    USER_ID INT PRIMARY KEY REFERENCES GYM_USERS(USER_ID) ON DELETE CASCADE,
    DATE_OF_BIRTH DATE,
    ADDRESS VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS TRAINERS (
    USER_ID INT PRIMARY KEY REFERENCES GYM_USERS(USER_ID) ON DELETE CASCADE,
    TRAINING_TYPE_ID INT,
    FOREIGN KEY (TRAINING_TYPE_ID) REFERENCES TRAINING_TYPES(TRAINING_TYPE_ID)
);

CREATE TABLE IF NOT EXISTS TRAININGS (
    TRAINING_ID SERIAL PRIMARY KEY,
    CUSTOMER_ID INT,
    TRAINER_ID INT,
    TRAINING_NAME VARCHAR(255) NOT NULL,
    TRAINING_TYPE_ID INT,
    TRAINING_DATE DATE NOT NULL,
    TRAINING_DURATION INT NOT NULL,
    FOREIGN KEY (TRAINING_TYPE_ID) REFERENCES TRAINING_TYPES(TRAINING_TYPE_ID),
    FOREIGN KEY (TRAINER_ID) REFERENCES TRAINERS(USER_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(USER_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS CUSTOMERS_TRAINERS (
    CUSTOMER_ID INT,
    TRAINER_ID INT,
    PRIMARY KEY (CUSTOMER_ID, TRAINER_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (TRAINER_ID) REFERENCES TRAINERS(USER_ID) ON DELETE CASCADE
);


